// <auto-generated />
using Furnish.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Furnish.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20240410171413_second")]
    partial class second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Furnish.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = "Sofa",
                            ImageUrl = "~/images/sofa.png",
                            Name = "Navi",
                            Price = 649.99000000000001
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = "Bed",
                            ImageUrl = "~/images/WhiteBed.png",
                            Name = "Serta Peninsula",
                            Price = 899.99000000000001
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = "Table",
                            ImageUrl = "~/images/table.png",
                            Name = "Mobili Fiver",
                            Price = 945.99000000000001
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = "Chair",
                            ImageUrl = "~/images/product-1.png",
                            Name = "Ashley Cashton",
                            Price = 2299.9899999999998
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = "Sofa",
                            ImageUrl = "~/images/couch.png",
                            Name = "Llappuil",
                            Price = 649.99000000000001
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = "Bed",
                            ImageUrl = "~/images/yuhuashi.png",
                            Name = "Yuhuashi",
                            Price = 247.0
                        });
                });

            modelBuilder.Entity("Furnish.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            userId = 1,
                            Address = "123 Goose Arm Street",
                            Email = "sbarr@shaw.ca",
                            GivenName = "Spencer",
                            Password = "Abcd1234",
                            Role = "Administrator",
                            Surname = "Barr",
                            Username = "sbarr"
                        },
                        new
                        {
                            userId = 2,
                            Address = "21 Marina Court",
                            Email = "cbarr@shaw.ca",
                            GivenName = "Corrine",
                            Password = "Abcd1234",
                            Role = "Buyer",
                            Surname = "Barr",
                            Username = "cbarr"
                        });
                });

            modelBuilder.Entity("Furnish.Models.UserLogin", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("UserLogin");
                });
#pragma warning restore 612, 618
        }
    }
}
